import pathlib,json,re,itertools,collections,hashlib
from partition_data import *
W=pathlib.Path(__file__).parent; rows=json.loads((W/'inventory_before.json').read_text(encoding='utf-8')); plan=json.loads((W/'partition_plan.json').read_text()); profiles=json.loads((W/'profiles.json').read_text(encoding='utf-8'))
relations={}
def rel(a,b,kind,claims,owner,action,residual):relations[tuple(sorted((a,b)))]=dict(kind=kind,correspondence=claims,canonical_owner=owner,action=action,unique_residual=residual)
rel('FO','CO','S+C+V','FO valuation, alignment and operator superposition reappear in CO minimal contract/selection/same-frame fusion. Old 24-page CO mixed these foundations; revised 14-page CO moves them to FO.','FO for operator calculus; CO for typed compilation','Remove loose cross-folder foundations/PDF/review copies after hash verification; retain original handoff ZIP and predecessor as history.','CO S/T/H normalization/tabulation, fragment completeness, negative dispatcher and evidence contract.')
rel('FO','GU','S+C','GU fixed-frame lift (thm:lmlift) specializes FO valuation/coherence; GU proves only the representation facts needed for dispatch.','FO general LM calculus; GU guarded specialization','Retain necessary self-contained definitions/proof specialization; cross-cite FO and claim GU novelty only for interface/nonlinear payload.','GU zero-aware score semantics, affine/quadratic guard gap and exact three-probe atlas.')
rel('FJ','GU','V+C','Shared Evolving Propositions parent and sign conventions. FJ thm:T2/T3/T5/T6 classify regular realizability; GU thm:atlas/thm:collecting and nonlinear case analyze given scores.','FJ regularity; GU quotient/dispatch','Keep both current papers; parent PDF in FJ HISTORY; disclose lineage and cross-cite regularity versus extraction boundary.','Distinct finite-jet obstruction versus exact parameter atlas, certification and restricted dispatch.')
rel('FO','BR','S+C','BR LM algebra/pairing and valuation naturality restate foundations (BR sections Q1-Q3); idempotent obstruction and scalar-support bridge extend beyond them.','FO for LM calculus; BR enrichment/support/update','Retain short foundations restatement in the companion for readability; cite FO, do not claim it twice.','BR obstruction, chosen scalar enrichment, satisfiability/possibility and division-free update.')
rel('IP','SP','S+C','Both discuss C4 rotations, Boolean Hamming/norm obstacles and Boolean stage, but SP moves to signed/integral coefficients while IP stays in characteristic two.','SP for finite Boolean isometry boundary and signed lift; IP for intrinsic ring/unitaries/ANF','Split the two manuscript families into separate projects; retain self-contained foundational negative results with cross-citation; shared tables in program register.','SP typed integral/carry/phase-count synthesis; IP intrinsic nilpotent/phase-ANF results.')
rel('FO','IP','S+C','IP CM-to-polynomial substitution/nonlinearity bridge and operator-folding motivation intersect FO ANF correspondence and frame calculus.','FO base correspondence/ANF identities; IP phase-tag and nilpotent extension','Retain common algebra with explicit attribution; exclude generic Boolean closure from novelty.','IP phase-Mobius encoding, subset-interval kernel, unitary/splitter classification and interaction bound.')
rel('CO','IP','S+C','IP local substitution/fold-before-expand section motivates computation; CO formalizes pair judgments, provenance and admitted compiler rules.','IP algebraic phase/ANF substitution; CO typed pair compiler','Cross-cite algebraic substitution; do not advertise it as a second compiler or reuse performance claims across contracts.','CO formal soundness/completeness and matched evidence; IP algebraic encoding/readout limits.')
rel('P01','PC','S+H','P01 balanced-tensor/regular-expansion boundary overlaps PC obstruction/coarse realization. PC filter preorder, marked normalizer and retained/resolved disposal extend P01 static resource comparison.','P01 static Smith/coding/teleportation; PC process closure/conversion','Keep companion separate; P01 cites precise process contract, not an unrestricted completion of nonzero ring support.','PC negative conditioning results, closed changed binary model and disposal-sensitive activation.')
rel('P01','BR','S+H','P01 Appendix conditional formula interface summarizes BR chosen scalar enrichment and support/satisfiability bridge.','BR full bridge proof; P01 application to resources','Retain short appendix with explicit companion citation; shared result excluded from P01 novelty.','P01 all-bases chain-ring trichotomy and exact resource comparison; BR full effect/update construction.')
rel('PC','BR','S+H','BR nonzero tensor and primitive-conditioning closure failures coincide with PC opening obstruction examples.','PC full process boundary/completion; BR warning needed for bridge','Retain warning in BR and cross-cite PC; do not merge away different support and process constructions.','BR symbolic support theorem; PC closed binary operations, normalizer, filters and disposal.')
rel('AU','BR','S+E','Eighteen audit/evidence files shared; BR support/update differs from AU model-contract and resource correction audit. Closure warnings overlap.','AU canonical audit data/model corrections; BR bridge report','Retain package-relative duplicate data for self-contained reproducibility; record exact pairs and hashes.','BR idempotent/scalar/support construction; AU wider correction and finite-evidence ledger.')
rel('AU','P01','S+H','AU Smith-class/resource/teleportation and literal-versus-shared boundaries precede P01 general chain-ring statements.','AU historical finite evidence/corrections; P01 general trichotomy and d*h theorem','Retain audit and P01 source package; qualify generalization versus existing finite special cases.','P01 general ring/dimension proofs and coherent coding-versus-teleportation comparison.')
rel('AU','P02','S+H','AU/old snapshots and theorem bank contain modal algorithm/no-go context; P02 sharpens the charged access/readout contract and adaptive proofs.','P02 exact query theorem package; AU older corrections','Do not claim archive mentions are another query paper; cite relevant corrected model assumptions.','P02 general Deutsch/BV exact bounds and DJ one-query obstruction under explicit contract.')
rel('AU','PC','S+H','AU preparation closure and finite-copy/literal activation corrections overlap PC negative independence and retained/disposed phase analysis.','AU correction provenance; PC complete process theorem/counterexample package','Retain both; PC must distinguish its changed operations from original no-go contracts.','PC closed literal contract, Frobenius/normalizer/filter results and disposal-sensitive comparison.')
rel('AU','IP','S+H','AU derived phase ring/centralizer, corrected nilpotent and model ledger overlap IP scalar ring and readout boundaries.','IP intrinsic algebra paper; AU corrections controlling later use','Retain correction report and cross-cite; flag older IP interpretations in CLAIMS_AND_UNIQUENESS.','IP phase-ANF/subset-interval/shared-tag algebra; AU resource/probability/model corrections.')
rel('AU','SP','S+H','AU distinguishes Boolean, signed, shared and literal models; SP contains earlier Boolean norm/isometry failures and signed-lift correction ledger.','SP signed-lift construction; AU later controlling model distinctions','Retain SP as synthesis companion, apply AU qualifications in future revisions; do not rewrite historical manuscript.','SP integral intertwiner, carry correction and exact phase-count encoding.')
rel('AU','FO','C+H','AU native CM/LM type ledger depends on foundations; its resource/modal corrections are not FO operator-calculus results.','FO Boolean calculus; AU modal corrections','Keep definitions where necessary and cross-cite type boundary.','FO formula-valued coherence versus AU operational no-go/correction package.')
rel('P02','IP','C','Both discuss kickback/ANF and Deutsch/BV, but IP reads constructed patterns while P02 charges oracle access and requires exact recorded readout.','IP phase/ANF representation; P02 charged query complexity','Keep both, state access distinction; no non-core theorem equivalence inferred from algorithm names.','IP encoding/interaction bounds; P02 access lower bounds.')
rel('P02','SP','C','Signed quantum-style algorithm reproduction versus characteristic-two charged query bounds.','SP changed-scalar reproduction; P02 exact modal bounds','Keep model contracts separate and cite explicitly.','Different scalar/access hypotheses; no duplicated query-bound theorem identified.')
rel('P01','IP','C','Shared F2[u]/(u^4) example and nilpotent background; general resource classification differs from phase/pattern algebra.','IP intrinsic phase; P01 chain-ring resources','Retain common definitions as core, not duplicate-paper evidence.','P01 all-bases Smith resources; IP phase-ANF/unitary/splitter package.')
rel('P01','SP','C','Teleportation/coding words occur in different scalar models and different tasks.','P01 chain-ring exact resources; SP signed calibration','Retain typed model qualifications; no claim duplication inferred from topic alone.','General finite-chain-ring resource comparison versus integral/signed encoding.')
rel('BT','GR','S+V+E','GR v0.1-v0.5 antecedents include same-carrier relative complexes, repair/Horn/chain results and old block counterexamples. BT post-audit v2 strengthens the focused height-two theorem and replaces the principal eight-state example with seven states. Several verifier files are exact shared evidence.','BT current fixed-carrier theorem package; GR carrier-splitting theory and design interactions','Keep old notes as marked history; preserve self-contained BT verifier bundle; centralize duplicated general/design evidence inside GR.','GR changing quotient carrier, fiber-profile projection and restricted observation/scheduling questions; design 3/5-state interaction examples retained.')
rel('PL','GR','S+V+E','v0.8 core PDF in original GR is predecessor of PL v0.8.1; observation signature/refinement is shared foundation; old research ledger also copied in PL.','PL current core; GR carrier-changing and design research; GR ledger canonical','Move v0.8 to PL HISTORY; retain PL contextual ledger snapshot as labelled historical evidence.','GR fiber splitting, cone/fiber certificate hierarchy and interaction/design boundary.')
rel('PL','BT','C','BT logical-observation interpretation imports the T0 signature poset and factorization assumption from PL.','PL core framework; BT order-thinning theorems','Retain short common definitions and explicit citation; exclude basic topology from novelty.','BT incidence/collapse equivalence and sharp bit/height limits.')
rel('GU','GR','S (prospective)','Minimum exact dispatch is already a classical test/hitting-set formulation in GU. GR constrained observation selection must add safety/carrier constraints or a new restricted algorithm.','GU existing dispatch specialization; GR only its distinct corrected design question','Merge original observation-design folder into GR; keep as a subdirection with no renewed generic minimum-test novelty claim.','Carrier-changing certificates and joint/sequential safety examples; optimization theorem remains unproved.')
rel('CO','SC','S+H','SC performance/planning reports overlap CO P14 and compiler audits; later structural endpoints use different workloads and costs.','CO pair-compiler theorem/P14; SC only distinct endpoint-matched studies','Keep research direction conditional; cite archived source/raw records and exclude reused P14 from novelty.','Repeated restriction/decomposition/retrieval with independently reconciled evidence; currently no new confirmed speedup.')
rel('FO','SC','C','Structural-computation research uses native CM definitions and decomposition motivation from FO.','FO calculus; SC empirical task outcomes','Retain core references, gate performance claims on recovered data.','Task-matched implementation/reuse questions rather than another representation paper.')
rel('GU','SC','H','Original guard-synthesis folder reused one structural planning file; it does not prove a synthesis algorithm or performance result.','SC original broader planning document; GU nested synthesis brief','Replace thin copied folder with brief and exact canonical references.','SC broader empirical endpoints; GU nonlinear dispatch theorem.')
for p in P:
 if p['id']=='RG':continue
 rel(p['id'],'RG','H+E','Register/theorem bank, consolidated findings and frozen reproduction archives index or repeat this project; they are not a competing publication. '+p['excluded'],p['id']+' for project claims; RG for register/provenance/shared archives','Retain labelled archival release packages and canonical ownership links; do not count evidence duplication as research novelty.','Project-specific contribution: '+p['claims'][0])

def relation(a,b):
 if tuple(sorted((a,b))) in relations:return relations[tuple(sorted((a,b)))]
 groups={'cm':{'FO','CO','IP','SP','P01','P02','PC','BR','AU','SC','GU'},'top':{'PL','BT','GR'}}
 common=any(a in g and b in g for g in groups.values())
 return dict(kind='C' if common else 'N',correspondence='Shared program definitions/background only; no additional non-core claim correspondence identified in inspected sources.' if common else 'Different objects and theorem packages; no substantive correspondence identified in inspected sources.',canonical_owner='Each owns only its listed claims.',action='Keep boundaries in project claim statements; no semantic deletion.',unique_residual=BY[a]['claims'][0]+' / '+BY[b]['claims'][0])

def group_exact(records):
 by=collections.defaultdict(list)
 for x in records:by[x['sha256']].append(x)
 return [dict(sha256=h,bytes=v[0]['bytes'],instances=v) for h,v in by.items() if len(v)>1]
exact=group_exact(rows)
orig=sorted({x['folder'] for x in rows}); original_map={p['folder']:[p['id']] for p in P if p['folder'] not in {SIGNED,INTR}}
original_map.update({GS:['GU','SC'],ATLAS:['FO','RG'],MODAL:['IP','SP'],DESIGN:['GR'],PORT:[p['id'] for p in P]})
om=[]
for a,b in itertools.combinations(orig,2):
 shared=[g for g in exact if a in {x['folder'] for x in g['instances']} and b in {x['folder'] for x in g['instances']}]
 rs=[relation(x,y) for x in original_map[a] for y in original_map[b] if x!=y]
 if set(original_map[a])&set(original_map[b]):rs.insert(0,dict(kind='V+S+E',correspondence='Original folders contain the same owned family or its copied package; see exact path/hash groups and version map.',canonical_owner=', '.join(sorted(set(original_map[a])&set(original_map[b]))),action='Merge, brief, historical package or exact-copy removal as recorded per file.',unique_residual='Only distinct claims enumerated for the surviving project, not copied context material.'))
 om.append(dict(folder_a=a,folder_b=b,hash_groups=len(shared),a_files=sum(sum(x['folder']==a for x in g['instances']) for g in shared),a_bytes=sum(sum(x['bytes'] for x in g['instances'] if x['folder']==a) for g in shared),b_files=sum(sum(x['folder']==b for x in g['instances']) for g in shared),b_bytes=sum(sum(x['bytes'] for x in g['instances'] if x['folder']==b) for g in shared),relationships=rs))
final=[dict(a=a['id'],b=b['id'],**relation(a['id'],b['id'])) for a,b in itertools.combinations(P,2)]
stats=[]
for f in orig:
 items=[x for x in rows if x['folder']==f]; dup=[x for x in items if any(y['folder']!=f and y['folder']!=PORT for y in rows if y['sha256']==x['sha256'])]; substantive=[x for x in items if pathlib.PurePosixPath(x['path']).name not in {'SOURCE_MANIFEST_SHA256.csv','00_PUBLICATION_CONTEXT_2026-09-25.md'}]; ds=[x for x in dup if x in substantive]
 stats.append(dict(folder=f,files=len(items),bytes=sum(x['bytes'] for x in items),exact_cross_folder_files=len(dup),exact_cross_folder_bytes=sum(x['bytes'] for x in dup),content_files=len(substantive),content_bytes=sum(x['bytes'] for x in substantive),content_duplicate_files=len(ds),content_duplicate_bytes=sum(x['bytes'] for x in ds),denominator='All other non-portfolio folders; administrative context and SOURCE_MANIFEST excluded for content columns.'))

# Lexical screening supplements the claim comparison. Never use it as a deletion rule.
docs=[]
for x in profiles:
 if pathlib.PurePosixPath(x['path']).suffix.lower() not in {'.tex','.pdf','.md'}:continue
 if any(t in x['path'] for t in ['pasted','CM_LM_Publication_Consolidation_Evidence']):continue
 text=(W/'text'/(x['sha256']+'.txt')).read_text(encoding='utf-8')
 text=re.sub(r'\\[a-zA-Z]+\*?', ' ',text); words=re.findall(r'[a-z0-9]+',text.lower()); shingles={hashlib.blake2b(' '.join(words[i:i+5]).encode(),digest_size=8).digest() for i in range(len(words)-4)}
 if len(shingles)>100:docs.append((x,shingles))
hits=[]
for (a,sa),(b,sb) in itertools.combinations(docs,2):
 if a['path'].split('/')[0]==b['path'].split('/')[0]:continue
 n=len(sa&sb); contain=n/min(len(sa),len(sb)); jacc=n/len(sa|sb)
 if n>=100 and contain>=.30:
  hits.append(dict(a=a['path'],b=b['path'],a_sha256=a['sha256'],b_sha256=b['sha256'],shared_5grams=n,containment=round(contain,4),jaccard=round(jacc,4),interpretation='Lexical screening flag only; formulas, bibliography, quotations and archive versions can dominate. Claim decisions are in pairwise matrix.'))
for name,obj in [('exact_groups_before',exact),('folder_overlap_stats',stats),('pairwise_original',om),('pairwise_surviving',final),('semantic_screen_before',{'docs':len(docs),'threshold':'100 common five-word shingles and containment >= .30','hits':sorted(hits,key=lambda x:-x['containment'])})]:
 (W/(name+'.json')).write_text(json.dumps(obj,indent=2,ensure_ascii=False),encoding='utf-8')
print(json.dumps({'original_pairs':len(om),'surviving_pairs':len(final),'exact_groups':len(exact),'semantic_docs':len(docs),'semantic_hits':len(hits),'nondefault_relationships':len(relations)},indent=2))
